-- AddEventHandler('explosionEvent', function(_src, event)
-- 	for a, exp in pairs(Config.ExplotionsManager) do
-- 		if exp.id == event.explosionType then
-- 			ExplosionCreator[_src] = (ExplosionCreator[_src] or 0) + 1
-- 			if ExplosionCreator[_src] >= exp.maxexplosion then
--                 BanPlayer(_src, "Blacklist Explosion: Player maakte een blacklist expolsion ("..exp.name..") | ("..ExplosionCreator[_src].."/"..exp.maxexplosion..")")
-- 			end
-- 		end
-- 	end
-- 	if event.isAudible == false then
-- 		if Config.AntiSilentExplosion then
-- 			CancelEvent()
-- 			BanPlayer(_src, "Blacklist Explosion: Probeerde een silent explosion te maken!")
-- 		end
-- 	end

-- 	if event.isInvisible == true then
-- 		if Config.AntiInvisibleExplosion then
-- 			CancelEvent()
-- 			BanPlayer(_src, "Blacklist Explosion: Probeerde een invisible explosion te maken!")
-- 		end
-- 	end
-- end)